spring.application.name=hackathon

spring.datasource.url=jdbc:postgresql://localhost:5432/rural_advisory
spring.datasource.username=japmansingh
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect